# working_directory = "C:\\Users\\pakky"

[shell]
# program = "pwsh"
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d ubuntu"] #, "-- /home/pakky/.local/bin/zellij -l welcome"]

[font]
normal = { family = "CaskaydiaCove NF" }

[terminal]
osc52 = "CopyPaste"
